In [ ]:
from datasets import load_dataset
from transformers import AutoTokenizer, DataCollatorWithPadding

raw_datasets = load_dataset("glue", "mrpc")
checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)


def tokenize_function(example):
    return tokenizer(example["sentence1"], example["sentence2"], truncation=True)


tokenized_datasets = raw_datasets.map(tokenize_function, batched=True)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

mrpc/train-00000-of-00001.parquet:   0%|          | 0.00/649k [00:00<?, ?B/s]

mrpc/validation-00000-of-00001.parquet:   0%|          | 0.00/75.7k [00:00<?, ?B/s]

mrpc/test-00000-of-00001.parquet:   0%|          | 0.00/308k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3668 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/408 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1725 [00:00<?, ? examples/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/3668 [00:00<?, ? examples/s]

Map:   0%|          | 0/408 [00:00<?, ? examples/s]

Map:   0%|          | 0/1725 [00:00<?, ? examples/s]

In [ ]:
from transformers import TrainingArguments
training_args = TrainingArguments(
    "test-trainer",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    )

In [ ]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model,
    training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
)

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=690, training_loss=0.2938408865444902, metrics={'train_runtime': 187.7929, 'train_samples_per_second': 58.596, 'train_steps_per_second': 3.674, 'total_flos': 428577075854640.0, 'train_loss': 0.2938408865444902, 'epoch': 3.0})

In [ ]:
predictions = trainer.predict(tokenized_datasets["validation"])
predictions

PredictionOutput(predictions=array([[-2.5729249 ,  3.4713335 ],
       [ 2.5410707 , -3.36664   ],
       [ 0.76393354, -0.6445374 ],
       [-2.504624  ,  3.3561313 ],
       [ 2.421005  , -3.3371022 ],
       [-2.4409497 ,  3.3106213 ],
       [-2.4944623 ,  3.2311134 ],
       [-2.513741  ,  3.4311008 ],
       [-2.2207227 ,  2.7602644 ],
       [-2.5475185 ,  3.4369698 ],
       [-2.5636842 ,  3.475224  ],
       [ 2.1879272 , -3.0091329 ],
       [ 2.1346009 , -2.7376354 ],
       [-2.545489  ,  3.3426201 ],
       [-2.5830133 ,  3.4331782 ],
       [-2.0022674 ,  2.6163228 ],
       [-2.5866508 ,  3.444821  ],
       [ 2.355924  , -2.9642177 ],
       [-2.5728695 ,  3.4422972 ],
       [ 2.3058684 , -2.5804675 ],
       [ 1.9430592 , -2.4307344 ],
       [-2.1883583 ,  2.7472599 ],
       [ 2.0305312 , -2.537668  ],
       [-2.4998977 ,  3.4120722 ],
       [-2.5537179 ,  3.4106443 ],
       [-1.597102  ,  2.1596    ],
       [ 0.24760327,  0.08988573],
       [-2.5881853 ,  3.4531188 ],
       [-2.4206066 ,  3.283941  ],
       [-2.5360472 ,  3.4507961 ],
       [ 1.8185284 , -1.7513422 ],
       [-2.5736852 ,  3.4630783 ],
       [-2.561041  ,  3.3155155 ],
       [-2.0500135 ,  2.7141156 ],
       [-2.605277  ,  3.4329503 ],
       [-2.4857798 ,  3.3694701 ],
       [ 1.7988999 , -2.1882615 ],
       [ 2.4864266 , -3.294707  ],
       [-2.1607249 ,  2.7468667 ],
       [-2.5820928 ,  3.451464  ],
       [ 2.3612373 , -3.040012  ],
       [-2.5504904 ,  3.41261   ],
       [ 1.8547995 , -2.0464182 ],
       [ 1.7272654 , -2.323324  ],
       [-0.18287142,  0.56895095],
       [-2.5863733 ,  3.462599  ],
       [-2.5563285 ,  3.4258516 ],
       [ 2.3977182 , -3.1978939 ],
       [-2.5890982 ,  3.4219494 ],
       [-2.3523731 ,  3.2643173 ],
       [-2.33231   ,  2.8055048 ],
       [-2.551018  ,  3.3470335 ],
       [-2.4745073 ,  3.3584569 ],
       [-2.565165  ,  3.3493686 ],
       [-2.571128  ,  3.4272625 ],
       [-2.486348  ,  3.2424643 ],
       [-2.040952  ,  2.5416212 ],
       [-2.561047  ,  3.4355743 ],
       [-2.5871646 ,  3.4658694 ],
       [-2.4978502 ,  3.3198345 ],
       [-2.497805  ,  3.2540083 ],
       [-1.406676  ,  1.9741077 ],
       [-2.5653992 ,  3.4339573 ],
       [-2.558533  ,  3.375144  ],
       [-2.5963466 ,  3.3182266 ],
       [ 2.3453503 , -3.1584609 ],
       [-2.5636082 ,  3.459343  ],
       [-2.5835419 ,  3.4542193 ],
       [-0.39422095,  0.78987825],
       [-2.5832653 ,  3.4223495 ],
       [-2.5816488 ,  3.4094298 ],
       [-1.0217283 ,  1.2595241 ],
       [-2.5921884 ,  3.3356931 ],
       [-2.5300236 ,  3.421948  ],
       [-2.4204679 ,  3.1987798 ],
       [-2.516649  ,  3.3682628 ],
       [-2.5115883 ,  3.130717  ],
       [-2.5560489 ,  3.41859   ],
       [-2.5508144 ,  3.4139175 ],
       [-2.5334105 ,  3.3526943 ],
       [-2.0572574 ,  2.9253552 ],
       [-2.5515778 ,  3.4015818 ],
       [-2.5869853 ,  3.4429405 ],
       [ 0.96901166, -0.9477753 ],
       [-2.5478632 ,  3.4722705 ],
       [-0.52182466,  0.77186567],
       [-2.429459  ,  3.3105776 ],
       [-2.3035269 ,  2.8204901 ],
       [-2.567561  ,  3.4447086 ],
       [-2.5464149 ,  3.435835  ],
       [-2.3153358 ,  3.1731877 ],
       [-2.5767436 ,  3.4172897 ],
       [-2.5148845 ,  3.3880467 ],
       [-2.4670079 ,  3.3033183 ],
       [-2.59764   ,  3.4819238 ],
       [-2.5577378 ,  3.4482486 ],
       [ 2.4149225 , -3.1379368 ],
       [-2.4862947 ,  3.0792854 ],
       [-2.5431247 ,  3.3811917 ],
       [-2.5568109 ,  3.4267304 ],
       [-2.4863477 ,  3.3187833 ],
       [-0.04734642,  0.38088903],
       [-2.5374012 ,  3.2130022 ],
       [-2.5824857 ,  3.4410405 ],
       [ 0.07112837,  0.05509649],
       [-2.5490599 ,  3.3736532 ],
       [-2.2788372 ,  3.1644807 ],
       [ 1.5108076 , -1.8521304 ],
       [ 2.2064428 , -2.9911737 ],
       [-2.5496972 ,  3.3212004 ],
       [-2.2493854 ,  3.0839024 ],
       [-2.5491269 ,  3.382787  ],
       [-2.4011445 ,  3.2337227 ],
       [-2.5810997 ,  3.454136  ],
       [-2.3798633 ,  3.0046885 ],
       [ 1.3176844 , -1.3451729 ],
       [-2.573669  ,  3.4811385 ],
       [-2.5702462 ,  3.4305549 ],
       [-2.5787373 ,  3.4386723 ],
       [-2.6192803 ,  3.4813764 ],
       [-2.5645533 ,  3.433651  ],
       [-2.300655  ,  3.1971846 ],
       [ 2.2254322 , -2.62304   ],
       [-2.4727101 ,  3.3159025 ],
       [-2.5653532 ,  3.4385157 ],
       [-2.5623977 ,  3.4249744 ],
       [-2.618873  ,  3.336673  ],
       [ 2.446842  , -3.18043   ],
       [-2.5837226 ,  3.4835086 ],
       [-2.5701118 ,  3.3842762 ],
       [-2.5539134 ,  3.2637424 ],
       [ 1.4372613 , -1.588159  ],
       [-2.4913    ,  3.2713878 ],
       [-1.6573021 ,  2.250347  ],
       [-2.432088  ,  2.9277704 ],
       [-2.5410724 ,  3.2878225 ],
       [ 2.0169396 , -2.4308546 ],
       [ 2.3119578 , -2.9811494 ],
       [-2.5689294 ,  3.4410038 ],
       [-2.5189364 ,  3.4304419 ],
       [-2.5756073 ,  3.4664383 ],
       [-1.1925924 ,  1.7427527 ],
       [ 2.4657977 , -3.2999067 ],
       [-2.553111  ,  3.3688705 ],
       [ 2.564743  , -3.1888108 ],
       [-2.1921527 ,  2.9923983 ],
       [-2.5831265 ,  3.4553862 ],
       [-2.0086694 ,  2.9946063 ],
       [-0.16134071,  0.67167723],
       [-2.568477  ,  3.401271  ],
       [ 2.467553  , -3.2598743 ],
       [-1.1717355 ,  1.7198995 ],
       [-1.8294494 ,  2.1905751 ],
       [-2.5683763 ,  3.405571  ],
       [ 1.8836006 , -1.9961804 ],
       [-2.5960245 ,  3.4290695 ],
       [-2.5669372 ,  3.4360092 ],
       [-2.1023886 ,  2.539129  ],
       [ 2.2653465 , -2.9485075 ],
       [-2.491982  ,  3.2947454 ],
       [-2.4816408 ,  3.1401684 ],
       [-2.51082   ,  3.2814627 ],
       [-2.5525944 ,  3.4192688 ],
       [-2.5663302 ,  3.4417932 ],
       [-2.4749646 ,  3.29405   ],
       [-2.567561  ,  3.3329906 ],
       [-2.444056  ,  3.0815883 ],
       [ 1.6357415 , -1.9148732 ],
       [-2.4808652 ,  3.405332  ],
       [ 2.4290676 , -3.2626154 ],
       [-0.3368528 ,  0.5826412 ],
       [-1.1629257 ,  1.5473106 ],
       [-1.8369055 ,  2.1792762 ],
       [-2.5670114 ,  3.4215503 ],
       [-2.3956552 ,  3.298414  ],
       [-2.5335534 ,  3.4314039 ],
       [-2.5054128 ,  3.3439348 ],
       [ 1.891205  , -2.599945  ],
       [-2.551884  ,  3.4213653 ],
       [-2.5613506 ,  3.4066935 ],
       [ 1.46598   , -1.6419466 ],
       [-2.3537064 ,  2.9692023 ],
       [-2.5451086 ,  3.4288092 ],
       [-2.5859702 ,  3.4481196 ],
       [-2.3888621 ,  3.3461795 ],
       [-2.1959271 ,  2.8177023 ],
       [ 2.5391207 , -3.1279364 ],
       [-0.13007995,  0.4031839 ],
       [ 2.4786453 , -3.1407661 ],
       [-2.5216165 ,  3.306454  ],
       [-2.6055744 ,  3.451845  ],
       [ 2.4332445 , -3.2559886 ],
       [-2.1104364 ,  2.9489205 ],
       [-2.5731664 ,  3.4393077 ],
       [-1.6406207 ,  2.2596285 ],
       [-2.5459664 ,  3.3152654 ],
       [-2.5898185 ,  3.4680543 ],
       [ 2.1715755 , -2.5112908 ],
       [-2.4091387 ,  3.3238294 ],
       [-2.4451592 ,  3.2761621 ],
       [-2.5258818 ,  3.3123932 ],
       [-1.597813  ,  2.2129076 ],
       [-2.1536722 ,  2.6462243 ],
       [-2.4982395 ,  3.10785   ],
       [-2.4895642 ,  3.1286912 ],
       [ 1.8822502 , -2.5267699 ],
       [-2.581775  ,  3.4669087 ],
       [-2.5759947 ,  3.3794007 ],
       [ 1.7201076 , -1.7050241 ],
       [-1.8534746 ,  2.4205933 ],
       [-1.7204285 ,  2.4576411 ],
       [-2.5853164 ,  3.4499302 ],
       [-2.457099  ,  3.0581975 ],
       [ 2.4203055 , -3.029595  ],
       [-2.6041875 ,  3.303032  ],
       [-2.5975933 ,  3.4540293 ],
       [-2.4454973 ,  3.3252702 ],
       [-2.555678  ,  3.3799014 ],
       [ 2.3013864 , -3.0184    ],
       [-2.5674927 ,  3.252649  ],
       [-2.3297513 ,  2.959333  ],
       [-2.349122  ,  2.8833244 ],
       [-2.5951128 ,  3.4357443 ],
       [ 2.3716073 , -2.976851  ],
       [-2.5873344 ,  3.4151273 ],
       [-2.5398076 ,  3.3841085 ],
       [-2.5895565 ,  3.4521282 ],
       [-2.463541  ,  3.2746227 ],
       [-2.5183854 ,  3.361157  ],
       [-2.538687  ,  3.3175466 ],
       [-2.5566878 ,  3.4506392 ],
       [-2.5265205 ,  3.391406  ],
       [-2.0486412 ,  2.6572104 ],
       [ 1.4844801 , -1.5228655 ],
       [-1.4429988 ,  1.8492022 ],
       [-1.4546723 ,  1.8902098 ],
       [-2.5504315 ,  3.398596  ],
       [ 2.6073089 , -3.3102207 ],
       [-2.266819  ,  2.7704341 ],
       [-2.1553369 ,  2.8394277 ],
       [-2.36289   ,  3.1898577 ],
       [ 2.362947  , -3.0944235 ],
       [-2.364092  ,  2.898186  ],
       [-2.540476  ,  3.299592  ],
       [-2.5764096 ,  3.4049556 ],
       [-2.58068   ,  3.4826424 ],
       [-2.5704083 ,  3.294208  ],
       [-1.8069354 ,  2.1894298 ],
       [-2.5573    ,  3.3807843 ],
       [-2.5288165 ,  3.1276214 ],
       [-2.5604336 ,  3.4471297 ],
       [ 1.2885814 , -1.4950742 ],
       [-1.7075143 ,  2.3129296 ],
       [ 2.2455773 , -2.5987902 ],
       [ 1.6151611 , -2.0302727 ],
       [ 2.5423522 , -3.3896587 ],
       [-2.5239513 ,  3.42351   ],
       [-2.557397  ,  3.4444904 ],
       [-2.552261  ,  3.2308695 ],
       [-1.907581  ,  2.4502354 ],
       [-2.4971824 ,  3.3727055 ],
       [-2.4162714 ,  3.1563902 ],
       [-2.5270782 ,  3.3596888 ],
       [-2.289403  ,  2.8976607 ],
       [-1.8706087 ,  2.5074723 ],
       [-1.9033031 ,  2.4795966 ],
       [-2.503964  ,  3.3850605 ],
       [ 2.4487336 , -3.181909  ],
       [ 1.9836168 , -2.6010551 ],
       [-2.4908962 ,  3.4142544 ],
       [ 1.8861132 , -2.375325  ],
       [-2.5514562 ,  3.4553418 ],
       [-2.6078255 ,  3.375144  ],
       [-2.5655994 ,  3.437599  ],
       [-2.5313535 ,  3.421096  ],
       [-2.4124596 ,  3.2736003 ],
       [-2.5396438 ,  3.2280703 ],
       [-2.1507835 ,  2.624226  ],
       [-1.3883481 ,  1.6503953 ],
       [ 2.3629627 , -3.1297636 ],
       [-2.4150715 ,  3.2518604 ],
       [-2.4193916 ,  3.1426759 ],
       [ 1.8386664 , -2.1122642 ],
       [ 2.2749288 , -3.0980227 ],
       [ 1.3956168 , -1.4080313 ],
       [-2.5759864 ,  3.4271636 ],
       [-2.5784135 ,  3.4654229 ],
       [-1.9734869 ,  2.3961496 ],
       [-2.550505  ,  3.4253812 ],
       [-1.0694782 ,  1.3273001 ],
       [-2.1624484 ,  2.602678  ],
       [ 2.393774  , -3.1322825 ],
       [-2.5745425 ,  3.4448247 ],
       [-2.3807583 ,  3.2039013 ],
       [-2.5635264 ,  3.3241405 ],
       [ 2.0319772 , -2.5764184 ],
       [ 2.3641608 , -3.1462803 ],
       [-2.3442976 ,  2.944825  ],
       [-2.5730379 ,  3.4334679 ],
       [-0.00612867,  0.46757248],
       [-2.569662  ,  3.4157481 ],
       [-2.5790424 ,  3.4269712 ],
       [-2.512156  ,  3.3824716 ],
       [-0.06095361,  0.3609651 ],
       [-2.5945036 ,  3.4844525 ],
       [-2.5489087 ,  3.4225693 ],
       [ 2.3144453 , -2.941029  ],
       [-2.5703213 ,  3.44801   ],
       [ 2.3341496 , -3.0353796 ],
       [-1.9863565 ,  2.7223816 ],
       [-2.5650856 ,  3.436164  ],
       [-2.5306993 ,  3.428485  ],
       [-0.17914723,  0.4306409 ],
       [ 2.497121  , -3.3142009 ],
       [-2.5599916 ,  3.4469311 ],
       [ 0.4493064 , -0.30252692],
       [-2.412523  ,  3.173931  ],
       [-2.5884547 ,  3.4099312 ],
       [ 2.3817153 , -3.1474156 ],
       [ 1.9696033 , -2.4291828 ],
       [ 2.3808076 , -3.2078073 ],
       [ 2.514043  , -3.3400722 ],
       [ 2.2637966 , -2.9137073 ],
       [-1.6234312 ,  2.1426048 ],
       [ 0.8216046 , -0.68312126],
       [-2.5672607 ,  3.4224522 ],
       [-2.423298  ,  3.1389003 ],
       [-2.5677915 ,  3.4343638 ],
       [-2.543641  ,  3.434349  ],
       [-1.2154747 ,  1.6557467 ],
       [-2.5957475 ,  3.4358628 ],
       [-2.5726402 ,  3.4558365 ],
       [ 1.417915  , -1.4317327 ],
       [-2.3034792 ,  2.854008  ],
       [-2.5710948 ,  3.433477  ],
       [-2.5095959 ,  3.3921604 ],
       [-2.5433295 ,  3.41063   ],
       [-2.5737967 ,  3.4521947 ],
       [ 1.5710758 , -1.8260301 ],
       [-2.4073472 ,  3.2137558 ],
       [-2.558381  ,  3.4370675 ],
       [-2.5943282 ,  3.4245698 ],
       [ 2.3007486 , -2.818574  ],
       [ 1.4619423 , -1.4976165 ],
       [-2.5624466 ,  3.438087  ],
       [-2.5888658 ,  3.46833   ],
       [-2.5720787 ,  3.4448373 ],
       [-2.5484073 ,  3.4110935 ],
       [-2.086511  ,  2.6737597 ],
       [-2.4989061 ,  3.3728027 ],
       [-1.1866561 ,  1.5037103 ],
       [-2.5967875 ,  3.4866095 ],
       [-1.8747919 ,  2.5147786 ],
       [-2.5007484 ,  3.2972949 ],
       [ 1.4421029 , -1.6424879 ],
       [-1.5590672 ,  1.7973498 ],
       [-2.492465  ,  3.2540221 ],
       [-2.416668  ,  3.2600338 ],
       [-2.4793732 ,  3.1071546 ],
       [-2.5876746 ,  3.3285944 ],
       [-1.6461755 ,  2.0258286 ],
       [-2.52872   ,  3.2315538 ],
       [-2.5812345 ,  3.4559832 ],
       [-1.3880144 ,  1.6416886 ],
       [-2.5489886 ,  3.415373  ],
       [-2.580099  ,  3.4361022 ],
       [-2.5598757 ,  3.4009113 ],
       [-2.1917136 ,  3.045108  ],
       [ 2.1848762 , -2.5053606 ],
       [ 2.404147  , -3.1481268 ],
       [-2.419646  ,  3.3191216 ],
       [-2.5975204 ,  3.4356458 ],
       [-2.5840483 ,  3.438291  ],
       [-2.3826044 ,  3.3224125 ],
       [ 2.382901  , -2.9840412 ],
       [-1.6131369 ,  2.2020025 ],
       [-1.4272432 ,  1.8963543 ],
       [ 2.5428932 , -3.3828714 ],
       [-2.328827  ,  3.249949  ],
       [-2.5466032 ,  3.4174676 ],
       [-2.4887185 ,  3.0155196 ],
       [-2.5289514 ,  3.3975356 ],
       [-0.8220973 ,  1.1480235 ],
       [-2.5612888 ,  3.4635472 ],
       [-2.3770878 ,  2.9654648 ],
       [ 2.3062842 , -2.9964592 ],
       [-2.0566957 ,  2.5216813 ],
       [-1.5718489 ,  2.0753548 ],
       [-2.5738997 ,  3.4482522 ],
       [-1.2359914 ,  1.7111773 ],
       [-2.5918417 ,  3.439921  ],
       [-2.538536  ,  3.1971617 ],
       [-2.5371456 ,  3.427554  ],
       [-2.5555377 ,  3.400683  ],
       [-2.4808097 ,  3.340192  ],
       [-2.495386  ,  3.3306057 ],
       [-2.565012  ,  3.4108257 ],
       [-1.2119231 ,  1.5400214 ],
       [-2.2827866 ,  2.9281628 ],
       [-2.584125  ,  3.4791102 ],
       [ 2.164793  , -2.7868414 ],
       [-2.5744038 ,  3.481834  ],
       [-2.3440704 ,  2.868897  ],
       [ 2.3049247 , -3.1097655 ],
       [-1.9127116 ,  2.3647578 ],
       [-2.5799947 ,  3.4619424 ],
       [-2.11336   ,  2.660655  ],
       [-2.4589157 ,  3.3758094 ]], dtype=float32), label_ids=array([1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1]), metrics={'test_loss': 0.5796799659729004, 'test_runtime': 1.8404, 'test_samples_per_second': 221.695, 'test_steps_per_second': 14.128})

In [ ]:
import numpy as np
preds = np.argmax(predictions.predictions, axis=-1)

In [ ]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.28.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.4 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
import evaluate
metric = evaluate.load("glue", "mrpc")
metric.compute(predictions=preds, references=predictions.label_ids)

Downloading builder script: 0.00B [00:00, ?B/s]

{'accuracy': 0.8700980392156863, 'f1': 0.9118136439267887}

In [ ]:
def compute_metrics(eval_preds):
    metric = evaluate.load("glue", "mrpc")
    logits, labels = eval_preds
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [ ]:
training_args = TrainingArguments(
    "test-trainer",
    eval_strategy="epoch",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    weight_decay=0.01,
    fp16=True,
    learning_rate=2e-5,
    lr_scheduler_type="cosine",
    )

model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

trainer = Trainer(
    model,
    training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=690, training_loss=1.5288694519927537, metrics={'train_runtime': 174.6931, 'train_samples_per_second': 62.99, 'train_steps_per_second': 3.95, 'total_flos': 377531475559680.0, 'train_loss': 1.5288694519927537, 'epoch': 3.0})